version: '3'

services: 
  db:
    image: fauna/faunadb:latest
    volumes:
      - dbdata:/var/log/faunadb
    restart: always
    ports:
      - 8443:8443
  shell:
    build:
      context: .
    restart: always

volumes:
  dbdata:
